---
# Elasticsearch Ansible Playbook
- hosts: elastic
  user: vagrant
  sudo: yes
  roles:
    - { role: elastic, install_java: "false" }

- hosts: kibana
  user: vagrant
  sudo: yes
  roles:
    - { role: kibana, install_java: "false" }

- hosts: logstash
  user: vagrant
  sudo: yes
  roles:
    - { role: logstash, install_java: "false" }
