---
- hosts: elastic
  sudo: yes
  roles:
    - common
    - java
    - elastic

- hosts: kibana
  sudo: yes
  roles:
    - common
    - java
    - kibana

- hosts: logstash
  sudo: yes
  roles:
    - common
    - java
    - logstash

- hosts: logstash-forwarder
  sudo: yes
  roles:
    - common
    - logstash-forwarder
