---
- hosts: elastic
  sudo: yes
  roles:
    - common
    - java
    - elastic

- hosts: kibana
  user: vagrant
  sudo: yes
  roles:
    - common
    - java
    - kibana

- hosts: logstash
  user: vagrant
  sudo: yes
  roles:
    - common
    - java
    - logstash
