- name: set locale
  locale_gen: name='zh_TW.UTF-8'

- name: set timezone
  copy:
    content: 'Asia/Taipei'
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: update timezone

- name: Install python-software-properties
  apt: pkg=python-software-properties state=present update_cache=yes cache_valid_time={{apt_cache_valid_time}}

- name: Install common dependencies
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time={{apt_cache_valid_time}}
  with_items: apt_dependencies
