# Update repos
- name: Install python-software-properties
  apt: pkg=python-software-properties state=present update_cache=yes cache_valid_time={{apt_cache_valid_time}}

- name: Update repositories
  apt_repository: repo={{ item }} state=present update_cache=yes
  with_items: apt_repos

# Accept Oracle license
- name: Accept Oracle license prior JDK installation
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections; echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections creates=/usr/lib/jvm/java-7-oracle
  when: install_java

# Install Java
- name: Install Java
  apt: pkg={{apt_java_package}} state=present
  when: install_java

# Install dependencies
- name: Install dependencies
  apt: pkg={{ item }} state=present
  with_items: apt_dependencies

- name: Import Elastic GPG Key
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: Add Elast Repo into source list
  apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/{{ elasticsearch_repo_version }}/debian stable main' state=present

- name: Update apt-get
  apt: update_cache=yes

# Install Elastic
- name: Install dependencies
  apt: pkg={{ elasticsearch_pkg }} state=present

# Configure Elasticsearch Node
- name: Configuring Elasticsearch Node
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=root group=root mode=0644
  notify: Restart Elasticsearch
