logstash_repo_version: 1.5

ssl_cert_directory: /etc/pki/tls/certs
ssl_cert: logstash-forwarder.crt
ssl_key: logstash-forwarder.key

apt_cache_valid_time: 600 # seconds between "apt-get update" calls.
